CREATE OR REPLACE VIEW public.board_cards
WITH (security_invoker = on) AS
 SELECT l.id::text AS id,
    l.id AS lead_id,
    l.nome,
    l.telefone,
    l.email,
    l.imovel,
    l.valor,
    l.entrada,
    l.stage::text AS stage,
    l.corretor_id,
    l.origem,
    l.observacoes,
    l.ultima_interacao,
    COALESCE(l.data_c2s, l.created_at) AS data_entrada,
    l.data_c2s,
    l.created_at,
    l.stage_since,
    l.finalidade,
    l.estagio_imovel,
    l.documentacao_ok,
    l.visita_em,
    l.visita_realizada,
    l.visita_status,
    l.visita_motivo,
    l.visita_projeto,
    l.c2s_contact_id,
    false AS agenda_record,
    false AS encontrado_c2s,
    NULL::text AS corretor_agenda_nome,
    l.updated_at AS ordem
   FROM leads l
  WHERE l.stage <> ALL (ARRAY['visita'::lead_stage, 'visita_realizada'::lead_stage])
    AND NOT EXISTS (SELECT 1 FROM public.agenda_appointments a WHERE a.lead_id = l.id)
UNION ALL
 SELECT ('agenda:'::text || a.id) || ':agendado'::text AS id,
    NULL::uuid AS lead_id,
    a.cliente_nome AS nome,
    a.cliente_telefone AS telefone,
    NULL::text AS email,
    a.empreendimento AS imovel,
    0::numeric AS valor,
    0::numeric AS entrada,
    'visita'::text AS stage,
    a.corretor_id,
    'Agenda'::text AS origem,
    a.motivo AS observacoes,
    COALESCE(a.agenda_atualizado_em, a.visita_em) AS ultima_interacao,
    COALESCE(a.agenda_criado_em, a.created_at) AS data_entrada,
    COALESCE(a.agenda_criado_em, a.created_at) AS data_c2s,
    a.created_at,
    COALESCE(a.agenda_atualizado_em, a.created_at) AS stage_since,
    NULL::text AS finalidade,
    NULL::text AS estagio_imovel,
    false AS documentacao_ok,
    a.visita_em,
    a.status = 'realizado'::text AS visita_realizada,
    a.status AS visita_status,
    a.motivo AS visita_motivo,
    a.empreendimento AS visita_projeto,
    a.lead_id::text AS c2s_contact_id,
    true AS agenda_record,
    a.encontrado_c2s,
    a.corretor_nome AS corretor_agenda_nome,
    a.visita_em AS ordem
   FROM agenda_appointments a
UNION ALL
 SELECT ('agenda:'::text || a.id) || ':realizado'::text AS id,
    NULL::uuid AS lead_id,
    a.cliente_nome AS nome,
    a.cliente_telefone AS telefone,
    NULL::text AS email,
    a.empreendimento AS imovel,
    0::numeric AS valor,
    0::numeric AS entrada,
    'visita_realizada'::text AS stage,
    a.corretor_id,
    'Agenda'::text AS origem,
    a.motivo AS observacoes,
    COALESCE(a.agenda_atualizado_em, a.visita_em) AS ultima_interacao,
    COALESCE(a.visita_em, a.agenda_atualizado_em, a.created_at) AS data_entrada,
    COALESCE(a.visita_em, a.agenda_atualizado_em, a.created_at) AS data_c2s,
    a.created_at,
    COALESCE(a.agenda_atualizado_em, a.created_at) AS stage_since,
    NULL::text AS finalidade,
    NULL::text AS estagio_imovel,
    false AS documentacao_ok,
    a.visita_em,
    true AS visita_realizada,
    a.status AS visita_status,
    a.motivo AS visita_motivo,
    a.empreendimento AS visita_projeto,
    a.lead_id::text AS c2s_contact_id,
    true AS agenda_record,
    a.encontrado_c2s,
    a.corretor_nome AS corretor_agenda_nome,
    a.visita_em AS ordem
   FROM agenda_appointments a
  WHERE a.status = 'realizado'::text;

GRANT SELECT ON public.board_cards TO authenticated;